// Generated by https://quicktype.io

export interface CardItem {
  _id: string;
  konamiID?: string;
  name: string;
  type: Type;
  monsterType: MonsterType[];
  level?: number;
  race: string;
  attribute?: string;
  description: string;
  linkArrows: string[];
  popRank: number;
  deckTypes: string[];
  obtain: ObtainItem[];
  def?: number | null;
  atk?: number | null;
  scale?: number;
  ocgRelease?: string;
  alternateArt?: boolean;
  handtrap?: boolean;
  floodgate?: boolean;
  tcgRelease?: string;
  generic?: boolean;
}

export interface ObtainItem {
  amount: number;
  type: string;
}

export interface SourceItem {
  _id: string;
  name: string;
}

export enum MonsterType {
  Effect = "Effect",
  Fusion = "Fusion",
  Normal = "Normal",
  Pendulum = "Pendulum",
  Ritual = "Ritual",
  Synchro = "Synchro",
  Xyz = "XYZ",
}

export enum Type {
  Monster = "Monster",
  Spell = "Spell",
  Trap = "Trap",
}

export type ClassifiedCard = {
  name: string;
  text: string;
  types: Record<string, number>;
  meta: Meta;
};

export type MonsterMeta = {
  types: string[];
  race: string;
  attribute: string;
  atk: number;
  def: number;
};

export type OtherMeta = {
  type: string;
  kind: string;
};

export type Meta = {
  monster: MonsterMeta;
  other: OtherMeta;
  decktypes: string[];
  rating: number;
  archetype: string;
};

export type Archetype = {
  name: string;
  stats: Record<string, number>;
};
